#! /usr/bin/env python
# encoding: utf-8
#
# ecpp library build script
#
# Copyright 2013 Andreas Messer <andi@bastelmap.de>
#
# This file is part of the Embedded C++ Platform Project.
#
# Embedded C++ Platform Project (ECPP) is free software: you can
# redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later
# version.
#
# Embedded C++ Platform Project is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ECPP.  If not, see <http://www.gnu.org/licenses/>.
#
# As a special exception, the copyright holders of ECPP give you
# permission to link ECPP with independent modules to produce an
# executable, regardless of the license terms of these independent
# modules, and to copy and distribute the resulting executable under
# terms of your choice, provided that you also meet, for each linked
# independent module, the terms and conditions of the license of that
# module.  An independent module is a module which is not derived from
# or based on ECPP.  If you modify ECPP, you may extend this exception
# to your version of ECPP, but you are not obligated to do so.  If you
# do not wish to do so, delete this exception statement from your
# version.

def build(bld):
    source_common = [
      'ecpp/String.cpp',
      'ecpp/Time.cpp',
    ]

    sourcefiles = {
        'avr-' : [
            'ecpp/Target/AVR8/Memory.cpp',
            'ecpp/Target/AVR8/TWI.cpp',
        ],

        'default' : [
            'common/syscalls.cc',
        ],
    }

    for id,env in bld.all_envs.items():
        if env['ECPP_BUILDLIB']:

          if not env.get_flat('ECPP_ENVNAME'):
              bld.fatal('ECPP_ENVNAME not set for "%s"' % id)

          prefix = env['TOOL_PREFIX']

          source_target = sourcefiles.get(prefix, sourcefiles['default'])

          bld.ecpp_build(
              id       = id,
              target   = env.get_flat('ECPP_LIBNAME'),
              source   = source_target + source_common,
              includes = ['.'],
              export_includes = [bld.path],
              cflags   = ['-ffunction-sections', '-fdata-sections'],
              cxxflags = ['-ffunction-sections', '-fdata-sections'],
              features = 'cxx cxxstlib'
          )



